# Generated by Django 3.2.16 on 2023-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20231023_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_comments',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_comments',
            new_name='user',
        ),
    ]
